title: Reddit Controversy Project
description: A Supervised Learning Case Study
theme: jekyll-theme-cayman  # Options: jekyll-theme-cayman (Light/Blue) OR jekyll-theme-slate (Dark)
show_downloads: true